
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-aws-jackhoman-com-v1alpha1-iamrole
  failurePolicy: Fail
  name: miamrole.kb.io
  rules:
  - apiGroups:
    - aws.jackhoman.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - iamroles
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-aws-jackhoman-com-v1alpha1-iamrole
  failurePolicy: Fail
  name: viamrole.kb.io
  rules:
  - apiGroups:
    - aws.jackhoman.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - iamroles
  sideEffects: None
