# permissions for end users to view iamrolebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iamrolebinding-viewer-role
rules:
- apiGroups:
  - aws.jackhoman.com
  resources:
  - iamrolebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws.jackhoman.com
  resources:
  - iamrolebindings/status
  verbs:
  - get
